# embed_spirv.cmake - turn compiled SPIR-V modules into C arrays.
#
# Run in script mode:
#   cmake -DSPV_NAMES=... -DSPV_FILES=... -DOUTPUT_SOURCE=... -DOUTPUT_HEADER=...
#         -P embed_spirv.cmake
#
# The Vulkan backend used to fopen() each .spv through a path baked in at
# configure time, which only ever resolved on the build machine.  Embedding the
# modules in the library removes that dependency: a packaged toolbox carries its
# shaders with it.

if(NOT DEFINED SPV_NAMES OR NOT DEFINED SPV_FILES)
  message(FATAL_ERROR "SPV_NAMES and SPV_FILES are required.")
endif()
if(NOT DEFINED OUTPUT_SOURCE OR NOT DEFINED OUTPUT_HEADER)
  message(FATAL_ERROR "OUTPUT_SOURCE and OUTPUT_HEADER are required.")
endif()

list(LENGTH SPV_NAMES name_count)
list(LENGTH SPV_FILES file_count)
if(NOT name_count EQUAL file_count)
  message(FATAL_ERROR
    "SPV_NAMES (${name_count}) and SPV_FILES (${file_count}) must be the same length.")
endif()

set(header_body
"/* Generated by cmake/embed_spirv.cmake -- do not edit. */
#ifndef NLO_VK_SHADER_BLOBS_H
#define NLO_VK_SHADER_BLOBS_H

#include <stddef.h>
#include <stdint.h>

/** A SPIR-V module compiled into the library. */
typedef struct {
    const uint32_t* words;   /**< SPIR-V words, natural alignment. */
    size_t size_bytes;       /**< Module size in bytes. */
} nlo_spirv_blob;

")

set(source_body
"/* Generated by cmake/embed_spirv.cmake -- do not edit. */
#include \"vk_shader_blobs.h\"

")

math(EXPR last_index "${name_count} - 1")
foreach(index RANGE ${last_index})
  list(GET SPV_NAMES ${index} spv_name)
  list(GET SPV_FILES ${index} spv_file)

  if(NOT EXISTS "${spv_file}")
    message(FATAL_ERROR "SPIR-V module not found: ${spv_file}")
  endif()

  file(READ "${spv_file}" spv_hex HEX)
  string(LENGTH "${spv_hex}" hex_length)
  if(hex_length EQUAL 0)
    message(FATAL_ERROR "SPIR-V module is empty: ${spv_file}")
  endif()
  math(EXPR hex_remainder "${hex_length} % 8")
  if(NOT hex_remainder EQUAL 0)
    message(FATAL_ERROR
      "SPIR-V module is not a whole number of 32-bit words: ${spv_file}")
  endif()
  math(EXPR byte_count "${hex_length} / 2")

  # Split into 4-byte groups and reassemble each as a little-endian word, so the
  # generated constants are correct regardless of the host's byte order.
  string(REGEX MATCHALL "[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]"
         hex_words "${spv_hex}")

  set(word_lines "")
  set(column 0)
  set(current_line "   ")
  foreach(hex_word IN LISTS hex_words)
    string(SUBSTRING "${hex_word}" 0 2 byte0)
    string(SUBSTRING "${hex_word}" 2 2 byte1)
    string(SUBSTRING "${hex_word}" 4 2 byte2)
    string(SUBSTRING "${hex_word}" 6 2 byte3)
    string(APPEND current_line " 0x${byte3}${byte2}${byte1}${byte0}u,")
    math(EXPR column "${column} + 1")
    if(column EQUAL 6)
      list(APPEND word_lines "${current_line}")
      set(current_line "   ")
      set(column 0)
    endif()
  endforeach()
  if(NOT column EQUAL 0)
    list(APPEND word_lines "${current_line}")
  endif()
  string(JOIN "\n" word_block ${word_lines})

  string(APPEND header_body
    "extern const nlo_spirv_blob nlo_spirv_${spv_name};\n")

  string(APPEND source_body
"static const uint32_t nlo_spirv_words_${spv_name}[] = {
${word_block}
};

const nlo_spirv_blob nlo_spirv_${spv_name} = {
    nlo_spirv_words_${spv_name},
    ${byte_count}u
};

")
endforeach()

string(APPEND header_body "\n#endif /* NLO_VK_SHADER_BLOBS_H */\n")

# Only rewrite when the contents change, so downstream compilation is not
# invalidated on every build.
if(EXISTS "${OUTPUT_HEADER}")
  file(READ "${OUTPUT_HEADER}" existing_header)
else()
  set(existing_header "")
endif()
if(NOT existing_header STREQUAL header_body)
  file(WRITE "${OUTPUT_HEADER}" "${header_body}")
endif()

if(EXISTS "${OUTPUT_SOURCE}")
  file(READ "${OUTPUT_SOURCE}" existing_source)
else()
  set(existing_source "")
endif()
if(NOT existing_source STREQUAL source_body)
  file(WRITE "${OUTPUT_SOURCE}" "${source_body}")
endif()
