# SIMD dependency (SIMDe header-only) for vectorized kernels
find_package(simd QUIET)
if(NOT simd_FOUND)
  include(FetchContent)
  FetchContent_Declare(
    simd
    URL https://github.com/simd-everywhere/simde/archive/refs/heads/master.zip
  )
  FetchContent_MakeAvailable(simd)
  if(NOT TARGET simd::simd)
    add_library(simd INTERFACE)
    add_library(simd::simd ALIAS simd)
    target_include_directories(simd INTERFACE ${simd_SOURCE_DIR})
  endif()
endif()

string(TOUPPER "${NLO_CPU_SIMD_LEVEL}" NLO_CPU_SIMD_LEVEL_UPPER)
set(_nlo_simd_compile_opts "")
set(_nlo_simd_compile_defs "")

if(NLO_CPU_SIMD_LEVEL_UPPER STREQUAL "SCALAR")
  list(APPEND _nlo_simd_compile_defs NLO_SIMD_SCALAR_ENABLED=1)
elseif(NLO_CPU_SIMD_LEVEL_UPPER STREQUAL "AVX")
  if(MSVC)
    list(APPEND _nlo_simd_compile_opts /arch:AVX)
  elseif(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    list(APPEND _nlo_simd_compile_opts -mavx)
  endif()
  list(APPEND _nlo_simd_compile_defs NLO_SIMD_AVX_ENABLED=1)
elseif(NLO_CPU_SIMD_LEVEL_UPPER STREQUAL "AVX2")
  if(MSVC)
    list(APPEND _nlo_simd_compile_opts /arch:AVX2)
  elseif(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    list(APPEND _nlo_simd_compile_opts -mavx2 -mfma)
  endif()
  list(APPEND _nlo_simd_compile_defs NLO_SIMD_AVX2_ENABLED=1)
elseif(NLO_CPU_SIMD_LEVEL_UPPER STREQUAL "AUTO")
  if(MSVC)
    list(APPEND _nlo_simd_compile_opts /arch:AVX2)
    list(APPEND _nlo_simd_compile_defs NLO_SIMD_AVX2_ENABLED=1)
  elseif(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    list(APPEND _nlo_simd_compile_opts -mavx2 -mfma)
    list(APPEND _nlo_simd_compile_defs NLO_SIMD_AVX2_ENABLED=1)
  endif()
else()
  message(FATAL_ERROR "Invalid NLO_CPU_SIMD_LEVEL='${NLO_CPU_SIMD_LEVEL}'. Use AUTO, AVX2, AVX, or SCALAR.")
endif()

if(_nlo_simd_compile_opts)
  add_compile_options(${_nlo_simd_compile_opts})
endif()
if(_nlo_simd_compile_defs)
  add_compile_definitions(${_nlo_simd_compile_defs})
endif()
